-include local.mk

ifndef MAX_GAP
MAX_GAP = 15
endif

GCOV ?= gcov

CFLAGS = -std=c++23 -Wall -Werror -Wextra -Wshadow -Wno-gnu-conditional-omitted-operand -Wno-unused-parameter -Wno-unused-function -march=native -DMAX_GAP=$(MAX_GAP)

PERF_FLAGS = -Ofast -g -DNDEBUG -fopenmp
#PERF_FLAGS = -O0 -g -DDEBUG
TEST_PERF_FLAGS = -O0 -g -DDEBUG

DEBUG_FLAGS = -g -DDEBUG

ifdef VERBOSE
DEBUG_FLAGS += -DVERBOSE
endif

INCLUDE += -Iinclude -isystem deps/sdsl-lite/include -isystem deps/seqio/include -isystem deps/args -isystem deps/libbio/include -isystem deps/libbio/lib/range-v3/include

LIBS += -lboost_iostreams -lz -lgsl -lgslcblas -lm

HEADERS =	include/bits.hpp \
			include/fm_index.hpp \
			include/gapmer.hpp \
			include/gapmer_count.hpp \
			include/partial_count.hpp \
			include/seed_clusterer.hpp \
			include/seed_finder.hpp \
			include/string_buffer.hpp \
			include/util.hpp \
			include/dot_writer.hpp \
			include/version.hpp

ARGS = deps/args/args.hxx
SDSL_DIR = deps/sdsl-lite/lib

GTEST_DIR = deps/googletest
RAPIDCHECK_DIR = deps/rapidcheck

GFLAGS = -lpthread -DGTEST_ON -isystem $(GTEST_DIR)/googletest/include -isystem $(RAPIDCHECK_DIR)/include -isystem $(RAPIDCHECK_DIR)/extras/gtest/include -pthread -L $(GTEST_DIR)/build/lib -L $(RAPIDCHECK_DIR)/build

TEST_HPP = test/gapmer_tests.hpp test/util_tests.hpp test/gapmer_count_tests.hpp

.PHONY: clean all test cover

%/%.hpp:

motivating: motivating.cpp
	$(CXX) $(CFLAGS) $(PERF_FLAGS) -isystem deps/seqio/include motivating.cpp -o motivating

huddinge: huddinge.cpp include/util.hpp include/gapmer.hpp
	$(CXX) $(CFLAGS) $(PERF_FLAGS) $(INCLUDE) huddinge.cpp -o huddinge

seed_finder: seed_finder.o libbio_reader_adapter.o $(HEADERS) $(ARGS) deps/libbio/src/libbio.a | $(SDSL_DIR) $(ARGS_DIR) deps/libbio
	$(CXX) $(CFLAGS) $(PERF_FLAGS) $(INCLUDE) seed_finder.o libbio_reader_adapter.o -o seed_finder deps/libbio/src/libbio.a $(LIBS)

comp: comp.cpp include/util.hpp
	$(CXX) $(CFLAGS) $(PERF_FLAGS) $(INCLUDE) comp.cpp -o comp

huddinge_deb: huddinge.cpp $(HEADERS)
	$(CXX) $(CFLAGS) $(DEBUG_FLAGS) $(INCLUDE) huddinge.cpp -o huddinge_deb

seed_finder_deb: seed_finder.cpp $(HEADERS) $(ARGS) deps/libbio/src/libbio.a | $(SDSL_DIR) $(ARGS_DIR) deps/libbio
	$(CXX) $(CFLAGS) $(DEBUG_FLAGS) $(INCLUDE) seed_finder.cpp -o seed_finder_deb $(LIBS)

clean:
	rm -f huddinge huddinge_deb seed_finder seed_finder_deb comp
	rm -f test/test test/cover test/test.o test/cover.o
	rm -f *.gcov test/*.gcda test/*.gcno index.info
	rm -rf target/

$(SDSL_DIR):
	git submodule update --init

$(GTEST_DIR)/googletest:
	git submodule update --init

$(RAPIDCHECK_DIR):
	git submodule update --init

$(ARGS):
	git submodule update --init

deps/libbio:
	git submodule update --init --recursive

deps/libbio/src/libbio.a: deps/libbio/local.mk
	$(MAKE) -C deps/libbio src/libbio.a

deps/libbio/local.mk: local.mk
	cp local.mk deps/libbio/

local.mk:
	bash -c "[ -e local.mk ] || echo -n "" > local.mk"

$(GTEST_DIR)/build/lib/libgtest_main.a: | $(GTEST_DIR)/googletest
	(mkdir -p $(GTEST_DIR)/build && cd $(GTEST_DIR)/build && cmake -DCMAKE_C_COMPILER="$(CC)" -DCMAKE_CXX_COMPILER="$(CXX)" -DBUILD_SHARED_LIBS=OFF .. && $(MAKE))

$(RAPIDCHECK_DIR)/build/librapidcheck.a: | $(RAPIDCHECK_DIR)
	(mkdir -p $(RAPIDCHECK_DIR)/build && cd $(RAPIDCHECK_DIR)/build && cmake -DCMAKE_C_COMPILER="$(CC)" -DCMAKE_CXX_COMPILER="$(CXX)" -DBUILD_SHARED_LIBS=OFF -DRC_ENABLE_GTEST=ON .. && $(MAKE))

test/test.o: $(TEST_HPP) $(GTEST_HEADERS) $(HEADERS) test/test.cpp
	$(CXX) $(CFLAGS) $(GFLAGS) -c test/test.cpp -o test/test.o

test/test: $(GTEST_DIR)/build/lib/libgtest_main.a $(RAPIDCHECK_DIR)/build/librapidcheck.a $(TEST_HPP) $(HEADERS) test/test.cpp
	$(CXX) $(CFLAGS) $(GFLAGS) $(INCLUDE) $(TEST_PERF_FLAGS) test/test.cpp -o test/test -lgtest_main -lgtest -lrapidcheck $(LIBS)

test: test/test
	test/test $(ARG)

test/cover: $(GTEST_DIR)/build/lib/libgtest_main.a $(TEST_HPP) $(HEADERS) test/test.cpp
	$(CXX) -g --coverage -O1 $(CFLAGS) $(GFLAGS) $(INCLUDE) test/test.cpp -o test/cover -lgtest_main -lgtest -lrapidcheck -lgcov $(LIBS)

cover: test/cover
	rm -f *.gcov test/*.gcda coverage.info
	test/cover
	lcov -c --ignore-errors inconsistent,unused --directory test --output-file coverage.info --gcov-tool $(GCOV)
	lcov --remove coverage.info "/usr*" --output-file coverage.info
	genhtml coverage.info -o target

%.o: %.cpp
	$(CXX) -c -o $@ $(CFLAGS) $(PERF_FLAGS) $(INCLUDE) $<

# Output git tag or version hash to config.h.
include/version.hpp: SHELL := /bin/bash
include/version.hpp: .git
	VERSION_STR=`./git_version.sh`; \
	printf "// This file is automatically generated by Makefile.\n#include <string>\nnamespace sf {\n  constexpr static std::string const version{\"%s\"};\n}\n" "$${VERSION_STR}" > "$@"
